### ISSUE TITLE
Half Image Render in 1.8

### ISSUE THREAD

**Issue by hero887** [unascribed/BlockRenderer#11] opened 2016-09-01 02:20 UTC
Hello! So I love the mod concept but I'm making a wiki (in-game wiki) for a bunch of mods in a modpack I have created (minecraftuberverse.com) and I added your mod to test it out.

The issue is this: it renders all items _cut in half_! I'll attach the files. The 512x512 renders as nothing. the `+shift render renders cut in half. I set the GUI scale to normal and it does the same thing everytime. 

I would try the latest file, but the issue is that my modpack is for 1.8 not anything newer. Do you have a solution for the 1.8 ver.?
![2016-09-01_10 13 25_slimeball](https://cloud.githubusercontent.com/assets/7927068/18153094/bc0d2838-702d-11e6-92f8-6fc566fcbaa0.png)
![2016-09-01_10 13 26_slimeball](https://cloud.githubusercontent.com/assets/7927068/18153095/bc4c96bc-702d-11e6-8a34-881ff311bdf8.png)
![2016-09-01_10 14 40_book](https://cloud.githubusercontent.com/assets/7927068/18153097/bc4eaf88-702d-11e6-825e-25ed2346a4b4.png)
![2016-09-01_10 14 41_book](https://cloud.githubusercontent.com/assets/7927068/18153096/bc4d0ee4-702d-11e6-9269-c275652178f0.png)

**Comment by exaskye** [comment] 2016-09-01 03:03
Since you can't update, a "solution" is to leave your window at Minecraft's default size (854x480). You'll only get 480x480 renders, but this issue won't occur.

Alternatively, you can use the launcher options to start the game at 854x512, so you get 512x512 renders without this bug in the old version.

(Duplicate of #3)

**Comment by exaskye** [comment] 2016-12-02 05:44
Closing due to inactivity.

**Closed as completed by exaskye** 2016-12-02 05:44 UTC
Labels: s: Duplicate, s: Already Fixed
